apiVersion: v1
kind: Service
metadata:
  name: log-generator
spec:
  selector:
    app: log-generator
  ports:
    - port: 8090
      name: http
  # change to LoadBalancer if you want
  type: ClusterIP